POST http://localhost:8080/books
Content-Type: application/json


{
  "id": 2,
  "kirjoittaja": "KirjoittajaTest",
  "otsikko": "otsikkoTest",
  "isbn": "123456",
  "tagit": "tagitTest",
  "related": "relatedTest"
}